### ISSUE TITLE
Add ability to submit new SalesOrder front-to-back

### ISSUE THREAD

**Issue by paeilers** [techexpertio/mystore-jee#5]

**Comment by paeilers** [comment]
- Back-end
- [ ] Apply JPA annotations to the Entity layer
- [ ] Create back-end service for Catalog management
- [ ] Create back-end REST resource for Catalog access
- Front-end
- [ ] Create Catalog views(s)
- [ ] Create Catalog controller(s)
- [ ] Create Catalog service for communication with back-end

**Comment by techexpertio** [comment]
Get to work, Patty.  This is a big one.

**Comment by paeilers** [comment]
This has turned out to be twice as much the effort I originally thought it would be.

**Comment by paeilers** [comment]
Persisting the dependent Sales Order Lines needs to be initiated separately in order to synchronize/populate the foreign key to the Sales Order. JPA/EclipseLink will persist them at the same time as the Sales Order but with a zero value for the foreign key to Sales Order.
